setting:
  experiment_type: conditional_sampling # [train_in_kspace, test]
  method: diffusion

langevin:
  num_iters: 1000

MACNet_setting:
  MACNet_LossType: '' 
  model_path: ''

inverse_problems:
  blur:
    name: blur
    kernel_size: 61
    intensity: 3.0

  box_inpainting:
    name: inpainting
    mask_opt:
      mask_type: box
      mask_len_range: !!python/tuple [128, 129]  # for box
      image_size: 256
  
  random_inpainting:
    name: inpainting
    mask_opt:
      mask_type: random
      mask_prob_range: !!python/tuple [0.9, 0.9] 
      image_size: 256

  super_resolution: 
    name: super_resolution
    in_shape: !!python/tuple [1, 3, 256, 256]
    scale_factor: 4
  
  phase_retrieval:
    name: phase_retrieval

inverse_problem_solvers:
  dps:
    method: dps
    params:
      scale: 1.1
  dds:
    method: dds
    params:
      gamma: 0.95
      CG_iters: 5
  ddnm:
      method: ddnm
      params:
        gamma: 0
  classical_pnpscore:
      method: classical_pnpscore
      params:
        gamma: 0
  pnpscore:
      method: pnpscore
      params:
        gamma: 0
  diffpir:
    method: diffpir
    params:
      gamma: 0
  ddrm:
    method: ddrm
    params:
      gamma: 0

noisy_training_data:
  training_data_noiselevel: 0.05
  tau_SURE: 0.0
  lr_SURE: 0.0

train:
  batch_size: 1
  num_workers: 1
  lr: 0.0001
  compute_vb_loss: False
  activate_tv_loss: False
  lr_tv: 0

diffusion:
  diffusion_predtype: epsilon
  latent_type: image_space  # [image_space, measurement_space]
  noise_schedule: linear
  diffusion_model_type: unconditional_diffusion # [unconditional, measurement_conditional, mask_conditional]
  mask_condition_type: degrade_input # [none, concatenation, thresholding_masked_value]
  image_size: 256
  microbatch: -1
  learn_sigma: True
  in_channels: 3
  cond_channels: 0
  num_channels: 128
  num_res_blocks: 1
  channel_mult: ""
  class_cond: False
  use_checkpoint: False
  attention_resolutions: 16
  num_heads: 4
  num_head_channels: 64
  num_heads_upsample: -1
  use_scale_shift_norm: True
  dropout: 0.0
  resblock_updown: True
  use_fp16: False
  use_new_attention_order: False
  model_path: 
  use_ddim: false
  timestep_respacing: ''
  clip_denoised: True
  learnable_dataconsistency: False


dataset:
  dataset_name: ffhq
  mask_pattern: "randomly_cartesian"
  num_multi_slice: 3
  acceleration_rate: 4
  noise_snr: 40

test:
  diffusion:
    use_ddim: True
    ddim_eta: 0.85
    num_samples: 5
    timestep_respacing: 'ddim1000'
    clip_denoised: False

  ckpt_path: "ema_0.9999_350000.pt"
  desc: testing300slices